from config.mongo_config import db

scrapped=db['scrapped']
youtube=db['youtube']
youtubePosts=db['youtubePosts']
sessionDetails = db['sessionDetails']
twitterPosts=db['twitterPosts'] 
dailymotionPosts=db['dailymotionPosts']
newsPosts = db['newsPosts']
instagramPosts = db['instagramPosts']
facebookPosts = db['facebookPosts']
scrappedPosts = db['scrappedPosts']
users = db['users']
threadPosts=db['threadPosts']
DigiNews = db['DigiNews']
pinterestPosts = db['pinterestPosts']
newsSession = db['newsSession']
scrappedPostsTest=db['scrappedPostsTest']
twitterTokens = db['twitterTokens']
proxyIP=db['proxyIP']
isProxy=db['isProxy']
youtubeTokens=db['youtubeTokens']